
project_id = "hnrkipkckzosankwmlgx"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[auth]
enable_signup = true
enable_confirmations = true
email_confirm_url = "https://grow-with-mentor-ai.lovable.app/dashboard"

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Verify your email address - MentorAI"
content_path = "./supabase/functions/send-verification-email/index.ts"

[auth.hook.send_email]
enabled = true
uri = "https://hnrkipkckzosankwmlgx.supabase.co/functions/v1/send-verification-email"
secrets = ["SEND_EMAIL_HOOK_SECRET"]
